set(_CATKIN_CURRENT_PACKAGE "collaborative_fusion")
set(collaborative_fusion_VERSION "0.0.0")
set(collaborative_fusion_MAINTAINER "wlsdzyzl <wlsdzyzl@todo.todo>")
set(collaborative_fusion_PACKAGE_FORMAT "2")
set(collaborative_fusion_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_generation")
set(collaborative_fusion_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(collaborative_fusion_BUILDTOOL_DEPENDS "catkin")
set(collaborative_fusion_BUILDTOOL_EXPORT_DEPENDS )
set(collaborative_fusion_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(collaborative_fusion_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(collaborative_fusion_TEST_DEPENDS )
set(collaborative_fusion_DOC_DEPENDS )
set(collaborative_fusion_URL_WEBSITE "")
set(collaborative_fusion_URL_BUGTRACKER "")
set(collaborative_fusion_URL_REPOSITORY "")
set(collaborative_fusion_DEPRECATED "")